import './globals.css'
import { Roboto } from 'next/font/google'
const inter = Roboto({weight: '400', subsets:["latin"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='px-8 py-5 text-xl border-b'>
          CodewithGillnuame@gmail.com
        </header>
        <div>{children}</div>
        </body>
    </html>
  )
}
